### ISSUE TITLE
sequelize-typescript 추가 도입이 필요한가

### ISSUE THREAD

**Issue by asdfg32145** [hwanfront/rnt-sales#18]
관련 이슈: #17
Sequelize는 자체 TypeScript 정의를 제공한다.
## [sequelize with typescript](https://sequelize.org/docs/v6/other-topics/typescript/)
>INFO
We're working hard on making Sequelize a breeze to use in TypeScript. [Some parts](https://github.com/sequelize/sequelize/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3ARFC+label%3A%22type%3A+typescript%22) are still a work in progress. We recommend using [sequelize-typescript](https://www.npmjs.com/package/sequelize-typescript) to bridge the gap until our improvements are ready to be released.
## [sequelize-typescript](https://github.com/sequelize/sequelize-typescript)
Decorators and some other features for sequelize (v6).

**Comment by hwanfront** [comment]
꼭 필요해보이진 않습니다.
